apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pihole
  name: pihole-deployment
spec:
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      volumes:
        - name: pihole-pv
          persistentVolumeClaim:
            claimName: pihole-pvc
      containers:
        - name: pihole
          image: pihole/pihole:2025.11.1
          envFrom:
            - configMapRef:
                name: pihole-configs
            #- secretRef:
            #   name: pihole-secrets
          securityContext:
            capabilities:
              add: ["SYS_NICE"]
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
            - name: dns-udp
              containerPort: 53
#              hostPort: 53
              protocol: UDP
            - name: dns-tcp
              containerPort: 53
#              hostPort: 53
              protocol: TCP
          volumeMounts:
            - name: pihole-pv
              mountPath: "/etc/pihole"
          resources:
            limits:
              memory: "2G"
              cpu: "1"
            requests:
              memory: "1G"
              cpu: "1"  
      dnsConfig:
        nameservers:
          - 1.1.1.1
          - 8.8.8.8
      #hostNetwork: true
      #dnsPolicy: ClusterFirstWithHostNet