apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv
  namespace: pihole
spec:
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local
  hostPath:
    path: /etc/pihole
